webtalk_init -webtalk_dir C:/Users/student/Downloads/RV32I-Pipelined-Processor-main/RV32I-Pipelined-Processor-main/RV32I_SCDP/scdp/scdp.sim/sim_1/behav/xsim/xsim.dir/InstructionMemory_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 19 02:13:47 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "015145f9-cb21-4661-b7d7-3b3a5ae0eb38" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "420b7c8f7fae40128fe95f44c62356c6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "27 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3652133048 -regid "" -xml C:/Users/student/Downloads/RV32I-Pipelined-Processor-main/RV32I-Pipelined-Processor-main/RV32I_SCDP/scdp/scdp.sim/sim_1/behav/xsim/xsim.dir/InstructionMemory_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/student/Downloads/RV32I-Pipelined-Processor-main/RV32I-Pipelined-Processor-main/RV32I_SCDP/scdp/scdp.sim/sim_1/behav/xsim/xsim.dir/InstructionMemory_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/student/Downloads/RV32I-Pipelined-Processor-main/RV32I-Pipelined-Processor-main/RV32I_SCDP/scdp/scdp.sim/sim_1/behav/xsim/xsim.dir/InstructionMemory_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
